### ISSUE TITLE
No github.com/meros/go-tcplistener in your all repositories

### ISSUE THREAD

**Issue by qiwihui** [meros/go-echo-server#1]
What does this package "github.com/meros/go-tcplistener" do in your echo server?  Can you give the address? Thanks.

**Comment by meros** [comment]
I think I deleted that repo for being a  little too simplistic without realizing I had this project depending on it :-) I will fix this either by incorporating it into this repo or recreating it.

**Comment by meros** [comment]
I've readded the go-tcplistener repo. This is of course just example code. It's not meant for anything serious (unless counting education/experimantation serious) :)
